// src/whiskers-launcher/src/lib/components/slider-setting.svelte
<script lang="ts">
	import { createEventDispatcher } from 'svelte';
	import Slider from './slider.svelte';

	export let title: string;
	export let description: string;
	export let min: number;
	export let max: number;
	export let step: number;
	export let value: number;

	let dispatch = createEventDispatcher();

	function onSlide(event: CustomEvent<number>) {
		dispatch('slide', event.detail);
	}
</script>

<div>
	<p class=" text-xl font-medium">{title}</p>
	<p class=" text-sub-text">{description}</p>
</div>
<Slider {min} {max} {step} {value} on:slide={onSlide} />

// src/whiskers/src/components/SliderSetting.vue
<script setup lang="ts">
import { PropType } from "vue";
import Slider from "./Slider.vue";
import { Theme } from "@/pages/Settings/ViewModel";

const emit = defineEmits(["updateValue"]);

const props = defineProps<{
    title: string,
    description: string,
    value: number,
    min: number,
    max: number,
    step: number,
    theme: Theme
}>();
</script>

<template>
    <div class="mr-2 ml-2">
        <div>
            <div class="title">{{ props.title }}</div>
            <div>{{ props.description }}</div>
        </div>

        <Slider class="mt-2" :min="props.min" :max="props.max" :step="props.step" :value="props.value" :theme="props.theme"
            @update:value="emit('updateValue', $event)" />
    </div>
</template>
