// src/pages/Dialogs/ExtensionDialog.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { getTheme } from '../Settings/Settings';
import { listen } from '@tauri-apps/api/event';
import { DialogResult, DialogFieldResult, DialogAction, CheckOption, SelectOption } from '@/data';
import { invoke } from '@tauri-apps/api';
import ChevronDown from "@icons/chevron-down.svg"
import PrimaryButton from '@/components/PrimaryButton.vue';
import Switch from '@/components/Switch.vue';

const updateThemeListener = ref();
const backgroundColor = ref("");
const secondaryBackgroundColor = ref("");
const tertiaryBackgroundColor = ref("");
const textColor = ref("");
const secondaryTextColor = ref("");
const accentColor = ref("");
const dialogAction = ref<DialogAction>();

onMounted(async () => {

    loadTheme();

    updateThemeListener.value = listen("update-theme", (_) => {
        loadTheme();
    });

    dialogAction.value = await invoke("get_dialog_action");

    console.log(dialogAction.value)
});


async function loadTheme() {

    let theme = await getTheme();
    backgroundColor.value = theme.background;
    secondaryBackgroundColor.value = theme.secondary_background;
    tertiaryBackgroundColor.value = theme.tertiary_background;
    textColor.value = theme.text;
    secondaryTextColor.value = theme.secondary_text;
    accentColor.value = theme.accent;
}

function getSelectValue(fieldID: string): string {

    let field = dialogAction.value?.fields.find(field => field.id === fieldID);

    return field !== undefined ? String(field.default_value) : ""
}

function finish() {

    let results: DialogFieldResult[] = [];

    dialogAction.value!!.fields!!.forEach((field) => {

        if (field.type === "Input") {
            results.push({
                field_id: field.id,
                value: (document.getElementById(field.id) as HTMLInputElement).value
            })
        }

        if (field.type === "Select") {
            results.push({
                field_id: field.id,
                value: (document.getElementById(field.id) as HTMLSelectElement).value
            })
        }

        if (field.type === "Toggle") {
            results.push({
                field_id: field.id,
                value: String((document.getElementById(field.id) as HTMLInputElement).checked)
            })
        }

        if (field.type === "CheckGroup") {

            interface OptionValue {
                id: string,
                checked: boolean
            }

            var value: OptionValue[] = [];

            field.options?.forEach((option) => {
                let checked = (document.getElementById(`${field.id}-${option.id}`) as HTMLInputElement).checked
                value.push({
                    id: option.id,
                    checked: checked
                })
            });


            results.push({
                field_id: field.id,
                value: JSON.stringify(value)
            });
        }
    })

    let dialogResult: DialogResult = {
        extension_id: dialogAction.value!!.extension_id,
        action: dialogAction.value!!.action,
        results: results
    }

    invoke("write_dialog_result", { result: dialogResult })
}

</script>
<template>
    <div class="p-4 main h-screen overflow-auto flex flex-col">
        <div class="flex-grow">
            <div v-for="field in dialogAction?.fields" class="field">
                <div v-if="field.type === 'Toggle'">
                    <div class="flex">
                        <div class="flex-grow">
                            <div class="font-bold">{{ field.title }}</div>
                            <div>{{ field.description }}</div>
                        </div>
                        <div>
                            <Switch :id="field.id" :checked="Boolean(field.value)" />
                        </div>
                    </div>
                </div>
                <div v-else-if="field.type === 'CheckGroup'" :id="field.id">
                    <div class="font-bold mb-4 text-lg">{{ field.title }}</div>
                    <div v-for="option in (field.options as CheckOption[])" class="flex mb-2">
                        <div class="flex-grow">
                            <div class="font-bold">{{ option.title }}</div>
                            <div>{{ option.description }}</div>
                        </div>
                        <div>
                            <Switch :id="`${field.id}-${option.id}`" :checked="Boolean(option.checked)" />
                        </div>
                    </div>
                </div>
                <div v-else>
                    <div class="font-bold ml-2">{{ field.title }}</div>
                    <div class="ml-2">{{ field.description }}</div>

                    <input v-if="field.type === 'Input'" :value="field.value" :id="field.id" class="input" :placeholder="field.placeholder">

                    <div v-if="field.type === 'Select'" class="select flex items-center">
                        <select class="select-input" :id="field.id" :value="getSelectValue(field.id)">
                            <option v-for="option in (field.options as SelectOption[])" :value="option.id">{{ option.value
                            }}</option>
                        </select>

                        <ChevronDown class="h-3 w-3 select-chevron" />
                    </div>
                </div>
            </div>
        </div>

        <PrimaryButton :text="dialogAction?.button_text ?? ''" :expand="true" @click="finish()" />
    </div>
</template>

<style scoped>
.main {
    background-color: v-bind(backgroundColor);
    color: v-bind(textColor);
}

.field {
    background-color: v-bind(secondaryBackgroundColor);
    margin-bottom: 8px;
    padding: 16px;
    border-radius: 24px;
}

.input {
    background-color: v-bind(tertiaryBackgroundColor);
    padding: 8px;
    padding-right: 16px;
    padding-left: 16px;
    width: 100%;
    border-radius: 48px;
    margin-top: 8px;
}

.input::placeholder {
    color: v-bind(secondaryTextColor);
}

.select {
    -webkit-appearance: none;
    appearance: none;
    border-radius: 48px;
    background-color: v-bind(tertiaryBackgroundColor);
    overflow: hidden;
}

.select-input {
    -webkit-appearance: none;
    appearance: none;
    background-color: v-bind(tertiaryBackgroundColor);
    width: 100%;
    outline: none;
    cursor: pointer;
    padding: 8px;
    padding-left: 16px;
    padding-right: 16px;
}

.select-chevron {
    margin-right: 16px;
    fill: v-bind(secondaryTextColor);
}
</style>

// src/whiskers-launcher/src/routes/extension-dialog/+page.svelte
<script lang="ts">
	import PrimaryButton from '$lib/components/primary-button.svelte';
	import InputSetting from '$lib/components/input-setting.svelte';
	import ToggleSetting from '$lib/components/toggle-setting.svelte';
	import TextAreaSetting from '$lib/components/text-area-setting.svelte';
	import SelectSetting from '$lib/components/select-setting.svelte';
	import FolderIcon from '$lib/icons/folder.svg?component';
	import {
		getSettings,
		getThemeCss,
		type DialogAction,
		type DialogResult,
		type Field,
		type FilePickerField,
		type SelectOption,
		type Settings
	} from '$lib/settings/settings';
	import { invoke } from '@tauri-apps/api';
	import { onMount } from 'svelte';
	import type { SelectValue } from '$lib/components/classes';
	import type { DialogFilter, OpenDialogOptions } from '@tauri-apps/api/dialog';
	import { open } from '@tauri-apps/api/dialog';

	let settings: Settings | null = null;
	let css = '';
	let action: DialogAction | null = null;
	let fields: Field[] = [];
	let results: DialogResult[] = [];

	onMount(async () => {
		settings = await getSettings();
		css = getThemeCss(settings);
		action = await invoke('get_dialog_request');
		fields = action!!.fields;

		console.log(JSON.stringify(fields));

		fields.forEach((field) => {
			let value = '';

			switch (field.field_type) {
				case 'Input':
					value = field.input_field!!.default_value;
					break;
				case 'TextArea':
					value = field.text_area_field!!.default_value;
					break;
				case 'Toggle':
					value = field.toggle_field!!.default_value.toString();
					break;
				case 'Select':
					value = field.select_field!!.default_value;
					break;
				case 'FilePicker':
					value = field.file_picker_field!!.default_path ?? '';
					break;
			}

			results.push({
				field_id: field.id,
				field_value: value,
				args: field.args
			});
		});
	});

	function getFieldValue(id: string): string {
		for (const index in results) {
			let result = results[index];

			if (result.field_id === id) {
				return result.field_value;
			}
		}

		return '';
	}

	function updateFieldValue(fieldId: string, value: string) {
		let newResults: DialogResult[] = [];

		results.forEach((result) => {
			if (result.field_id === fieldId) {
				let newResult = result;
				newResult.field_value = value;
				newResults.push(newResult);
			} else {
				newResults.push(result);
			}
		});

		results = [...newResults];
		fields = [...fields];
	}

	function getSelectValues(fieldId: string): SelectValue[] {
		let values: SelectValue[] = [];

		fields.forEach((field) => {
			if (field.id === fieldId) {
				field.select_field?.options.forEach((option) => {
					values.push({
						id: option.id,
						value: option.value
					});
				});
			}
		});

		return values;
	}

	function getBoolean(value: string): boolean {
		return value === 'true';
	}

	async function openPicker(id: string, field: FilePickerField) {
		let options: OpenDialogOptions = {};

		if (field.pick_directory) {
			options.directory = true;
		}

		if (field.default_path) {
			options.defaultPath = field.default_path;
		}

		if (field.filters) {
			let filters: DialogFilter[] = [];

			field.filters.forEach((filter) => {
				filters.push({
					name: filter.name,
					extensions: filter.extensions
				});
			});

			options.filters = filters;
		}

		const path = await open(options);

		if (path && !Array.isArray(path)) {
			updateFieldValue(id, path);
		}
	}

	function runAction() {
		invoke('run_dialog_action', { action: action!!, results: results });
	}
</script>

{#if settings !== null && action !== null}
	{@html css}
	<div class=" p-4 gap-4 bg-background text-text h-screen w-full flex flex-col">
		<div class=" flex-grow space-y-4 overflow-auto">
			{#each fields as field}
				{#if field.field_type === 'Input'}
					<InputSetting
						title={field.input_field?.title}
						description={field.input_field?.description}
						placeholder={field.input_field?.placeholder}
						value={getFieldValue(field.id)}
						on:input={(event) => {
							updateFieldValue(field.id, event.detail);
						}}
					/>
				{/if}
				{#if field.field_type === 'TextArea'}
					<TextAreaSetting
						title={field.text_area_field?.title}
						description={field.text_area_field?.description}
						placeholder={field.text_area_field?.placeholder}
						value={getFieldValue(field.id)}
						on:input={(event) => {
							updateFieldValue(field.id, event.detail);
						}}
					/>
				{/if}
				{#if field.field_type === 'Toggle'}
					<ToggleSetting
						title={field.toggle_field?.title ?? ''}
						description={field.toggle_field?.description ?? ''}
						toggled={getBoolean(getFieldValue(field.id))}
						on:toggle={(event) => {
							updateFieldValue(field.id, event.detail.toString());
						}}
					/>
				{/if}
				{#if field.field_type === 'Select'}
					<SelectSetting
						title={field.select_field?.title ?? ''}
						description={field.select_field?.description ?? ''}
						values={getSelectValues(field.id)}
						selectedValue={getFieldValue(field.id)}
						on:selection={(event) => {
							updateFieldValue(field.id, event.detail.id);
						}}
					/>
				{/if}
				{#if field.field_type === 'FilePicker'}
					<div class=" card space-y-2">
						<div>
							<p class=" text-xl font-medium">{field.file_picker_field?.title}</p>
							<p class=" text-sub-text">{field.file_picker_field?.description}</p>
						</div>
						<button
							class=" flex gap-4 w-full items-center bg-background p-2 rounded-md border-tertiary"
							on:click={() =>
								field.file_picker_field && openPicker(field.id, field.file_picker_field)}
						>
							<FolderIcon class=" h-8 w-8" />
							<p class=" one-line">
								{getFieldValue(field.id) === ''
									? `Click here to select a ${field.file_picker_field?.pick_directory ? 'directory.' : 'file.'}`
									: getFieldValue(field.id)}
							</p>
						</button>
					</div>
				{/if}
			{/each}
		</div>
		<div class=" flex justify-end">
			<PrimaryButton text={action.action_text} on:click={runAction} />
		</div>
	</div>
{/if}
